// WARNING: This file will be automatically regenerated by the Froley compiler.
// Any edits will be lost!

package froley.demo.json;

class CmdFactory
{
  // GLOBAL METHODS
  static public Cmd createCmd( int index, Token t, CmdInitArgs args )
  {
    switch (index)
    {
      case 0 : return new Cmd.CmdObject().init( t, args );
      case 1 : return new Cmd.CmdArray().init( t, args );
      case 2 : return new Cmd.CmdString().init( t, args );
      case 3 : return new Cmd.CmdNumber().init( t, args );
      case 4 : return new Cmd.CmdTrue().init( t, args );
      case 5 : return new Cmd.CmdFalse().init( t, args );
      case 6 : return new Cmd.CmdNull().init( t, args );
      case 7 : return new Cmd.CmdMapping().init( t, args );
      default:
        throw new Error( "RogueFroley", "[INTERNAL] CmdFactory.createCmd() index out of bounds: " + index );
    }
  }
}
