package froley.demo.json;

public class Code
{
  // PROPERTIES
  static String tokenizerCode =
    "AQcIdG9rZW5pemUnU3ludGF4IGVycm9yIC0gdW5yZWNvZ25pemVkIGlkZW50aWZp" +
    "ZXIuG1N5bnRheCBlcnJvciAtIHVuZXhwZWN0ZWQgJwInLg9EaWdpdCBleHBlY3Rl" +
    "ZC4uU3ludGF4IGVycm9yIC0gdW5yZWNvZ25pemVkIGVzY2FwZSBzZXF1ZW5jZSAn" +
    "XBNDbG9zaW5nICIgZXhwZWN0ZWQuAQAAgbI0AQQgDQkSChcNHAYhAQABBiEBAAEG" +
    "IQEAAQYhAQABBiEEDwsoAAYoFQp5NQEDZjpuUXRkFhkBAwZ3AAFhPgABbEIAAXNG" +
    "AAFlSgEABQgBBncAAXVVAAFsWQABbF0BAAUJAQZ3AAFyaAABdWwAAWVwAQAFCgEG" +
    "dwZ5NAEHXYCcfYCjOoCqLICxW4C4e4C/IoDGEAAiCgiAliAtB4CWBoCaDYDVBoCa" +
    "BoDMAQAFCwEGgMwBAAUMAQaAzAEABQ0BBoDMAQAFDgEGgMwBAAUPAQaAzAEABRAB" +
    "BoDMAQANgSsGgMwWGQIQABcZAwMWEy0KgN4YLQaA3hMwCoDmGDAGgOgNgRQTLgqA" +
    "8hguDYEUBoDyE2ULgPwTRQuA/AaBERhFEAATKwuBChMtC4EKBoENFwaBDQ2BFAaB" +
    "EQUHARAAIgoIgSAWGQQDBoEgBoEmEhcQACIKCIEiDhYQAAaBkxIgXAiBkDQBCSKB" +
    "VVyBWy+BYWKBZ2aBbW6Bc3KBeXSBf3WBhRYZBRAAFxkDAwaBjgEAGCIGgY4BABhc" +
    "BoGOAQAYLwaBjgEAGAgGgY4BABgMBoGOAQAYCgaBjgEAGA0GgY4BABgJBoGOAQAU" +
    "BAQQFwaBjgaBkRcQAA8KgaQgIgeBpCAgCYGkIH8HgaQGgTATIguBrhYZBgMGga4F" +
    "BgEA";

  static String parserCode =
    "AQQFdmFsdWULZGVmaW5pdGlvbnMKZGVmaW5pdGlvbgVhcnJheQQAAAE/AlMDYncG" +
    "EA0CPxEMCwABAQMNBg8aAmIRCwsBAQEDGgYGIQsCAAEGBygLAwABBgovCwQAAQYI" +
    "NgsFAAEGCT0LBgABAAEKCQwdBVECUwNLAlMQDgRJA1ENAQYGYBENAgALBwEBA2AA" +
    "AQoJCx0FdAIAA24CABAOBGwDdA0BAQ==";
}

