// WARNING: This file will be automatically regenerated by the Froley compiler.
// Any edits will be lost!

package froley.demo.json;

public class ParserOpcode
{
  final static public int SYNTAX_ERROR           =  0;
  final static public int RETURN                 =  1;
  final static public int CALL                   =  2;
  final static public int JUMP                   =  3;
  final static public int JUMP_IF_TRUE           =  4;
  final static public int JUMP_IF_FALSE          =  5;
  final static public int ON_TOKEN_TYPE          =  6;
  final static public int HAS_ANOTHER            =  7;
  final static public int NEXT_HAS_ATTRIBUTE     =  8;
  final static public int NEXT_IS_TYPE           =  9;
  final static public int BEGIN_LIST             = 10;
  final static public int CREATE_CMD             = 11;
  final static public int CREATE_NULL_CMD        = 12;
  final static public int CREATE_LIST            = 13;
  final static public int CREATE_STATEMENTS      = 14;
  final static public int CONSUME_EOLS           = 15;
  final static public int CONSUME_TYPE           = 16;
  final static public int MUST_CONSUME_TYPE      = 17;
  final static public int SAVE_POSITION          = 18;
  final static public int RESTORE_POSITION       = 19;
  final static public int DISCARD_SAVED_POSITION = 20;
  final static public int TRACE                  = 21;
  final static public int PRINTLN_STRING         = 22;
  final static public int PRINTLN_NUMBER         = 23;
  final static public int POP_DISCARD            = 24;
  final static public int PUSH_INT32             = 25;
  final static public int DECLARE_VAR            = 26;
  final static public int WRITE_VAR              = 27;
  final static public int READ_VAR               = 28;
  final static public int LOGICAL_NOT            = 29;
  final static public int COMPARE_EQ             = 30;
  final static public int COMPARE_NE             = 31;
  final static public int COMPARE_LT             = 32;
  final static public int COMPARE_LE             = 33;
  final static public int COMPARE_GT             = 34;
  final static public int COMPARE_GE             = 35;
}
