// WARNING: This file will be automatically regenerated by the Froley compiler.
// Any edits will be lost!

package froley.demo.json;

public class TokenTypeAttribute
{
  final static public int NONE    = 0;
  final static public int CONTENT = 1;
}

