// WARNING: This file will be automatically regenerated by the Froley compiler.
// Any edits will be lost!

package froley.demo.json;

public class TokenizerOpcode
{
  final static public int HALT                =  0;
  final static public int RESTART             =  1;
  final static public int MODE_INT32          =  2;
  final static public int ERROR               =  3;
  final static public int MARK_SOURCE_POS     =  4;
  final static public int CREATE_INT32        =  5;
  final static public int JUMP                =  6;
  final static public int JUMP_EQ             =  7;
  final static public int JUMP_NE             =  8;
  final static public int JUMP_LT             =  9;
  final static public int JUMP_LE             = 10;
  final static public int JUMP_GT             = 11;
  final static public int JUMP_GE             = 12;
  final static public int CALL                = 13;
  final static public int RETURN              = 14;
  final static public int HAS_ANOTHER         = 15;
  final static public int PEEK_CH_INT32       = 16;
  final static public int PEEK_CH_COUNT       = 17;
  final static public int READ_CH             = 18;
  final static public int CONSUME_CHARACTER   = 19;
  final static public int NEXT_IS_CHARACTER   = 20;
  final static public int SCAN_DIGITS         = 21;
  final static public int SCAN_IDENTIFIER     = 22;
  final static public int CLEAR_BUFFER        = 23;
  final static public int COLLECT_CH          = 24;
  final static public int COLLECT_CHARACTER   = 25;
  final static public int COLLECT_STRING      = 26;
  final static public int BUFFER_TO_LOWERCASE = 27;
  final static public int PRINT_BUFFER        = 28;
  final static public int PRINT_CH            = 29;
  final static public int PRINT_COUNT         = 30;
  final static public int PRINT_CHARACTER     = 31;
  final static public int PRINT_STRING        = 32;
  final static public int COMPARE_CH_INT32    = 33;
  final static public int COMPARE_COUNT_INT32 = 34;
  final static public int CH_IS_DIGIT_INT32   = 35;
  final static public int CH_IS_DIGIT_COUNT   = 36;
  final static public int CH_IS_LETTER        = 37;
  final static public int PUSH_CH             = 38;
  final static public int PUSH_COUNT          = 39;
  final static public int POP_CH              = 40;
  final static public int POP_COUNT           = 41;
  final static public int SET_CH_TO_INT32     = 42;
  final static public int SET_CH_TO_COUNT     = 43;
  final static public int SET_COUNT_TO_INT32  = 44;
  final static public int SET_COUNT_TO_CH     = 45;
  final static public int SET_RESULT_TO_CH    = 46;
  final static public int SET_RESULT_TO_COUNT = 47;
  final static public int SET_RESULT_TO_INT32 = 48;
  final static public int ADD_CH_COUNT        = 49;
  final static public int ADD_CH_INT32        = 50;
  final static public int ADD_COUNT_INT32     = 51;
  final static public int SUBTRACT_CH_COUNT   = 52;
  final static public int WHICH_INPUT         = 53;
  final static public int WHICH_BUFFER        = 54;
}
