// WARNING: This file will be automatically regenerated by the Froley compiler.
// Any edits will be lost!

package froley.demo.json;

public class TokenType
{
  final static public int EOI           =  1;
  final static public int SPACE         =  2;
  final static public int TAB           =  3;
  final static public int EOL           =  4;
  final static public int CR            =  5;
  final static public int STRING        =  6;
  final static public int NUMBER        =  7;
  final static public int FALSE         =  8;
  final static public int NULL          =  9;
  final static public int TRUE          = 10;
  final static public int CLOSE_BRACKET = 11;
  final static public int CLOSE_CURLY   = 12;
  final static public int COLON         = 13;
  final static public int COMMA         = 14;
  final static public int OPEN_BRACKET  = 15;
  final static public int OPEN_CURLY    = 16;

  static public int[]    attributes =
  {
    0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0
  };

  static public String[] symbols =
  {
    "end of input", " ", "TAB", "EOL", "CR", "string", "number", "false",
    "null", "true", "]", "}", ":", ",", "[", "{"
  };
}
